# Generated by Django 5.2.3 on 2025-06-30 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIntervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome Categoria')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('icona', models.CharField(blank=True, help_text="Classe CSS per l'icona (es. fas fa-hammer)", max_length=50, verbose_name='Icona CSS')),
                ('colore', models.CharField(default='#007bff', help_text='Codice colore esadecimale (es. #007bff)', max_length=7, verbose_name='Colore')),
                ('attiva', models.BooleanField(default=True, verbose_name='Categoria Attiva')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine di Visualizzazione')),
            ],
            options={
                'verbose_name': 'Categoria Intervento',
                'verbose_name_plural': 'Categorie Interventi',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('attiva', models.BooleanField(default=True, verbose_name='Iscrizione Attiva')),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('data_disiscrizione', models.DateTimeField(blank=True, null=True)),
                ('interesse_ristrutturazioni', models.BooleanField(default=True)),
                ('interesse_bonus', models.BooleanField(default=True)),
                ('interesse_consigli', models.BooleanField(default=True)),
                ('interesse_novita', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Iscrizione Newsletter',
                'verbose_name_plural': 'Iscrizioni Newsletter',
                'ordering': ['-data_iscrizione'],
            },
        ),
        migrations.CreateModel(
            name='ConsulenzaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('data_preferita', models.DateTimeField(verbose_name='Data e Ora Preferita')),
                ('data_confermata', models.DateTimeField(blank=True, null=True, verbose_name='Data e Ora Confermata')),
                ('descrizione_progetto', models.TextField(verbose_name='Descrizione del Progetto')),
                ('budget_orientativo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget Orientativo (€)')),
                ('urgenza', models.CharField(choices=[('nessuna', 'Nessuna Fretta'), ('entro_mese', 'Entro un Mese'), ('entro_settimana', 'Entro una Settimana'), ('urgente', 'Urgente')], default='nessuna', max_length=20, verbose_name='Urgenza')),
                ('stato', models.CharField(choices=[('richiesta', 'Richiesta Inviata'), ('confermata', 'Confermata'), ('completata', 'Completata'), ('annullata', 'Annullata'), ('no_show', 'Cliente Assente')], default='richiesta', max_length=15, verbose_name='Stato')),
                ('link_meeting', models.URLField(blank=True, verbose_name='Link Video Meeting')),
                ('note_consulente', models.TextField(blank=True, verbose_name='Note del Consulente')),
                ('valutazione_cliente', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Valutazione Cliente (1-5)')),
                ('feedback_cliente', models.TextField(blank=True, verbose_name='Feedback Cliente')),
                ('tipo_intervento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriaintervento', verbose_name='Tipo di Intervento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulenze', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulenza Video',
                'verbose_name_plural': 'Consulenze Video',
                'ordering': ['-data_richiesta'],
            },
        ),
        migrations.CreateModel(
            name='PacchettoRistrutturazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Pacchetto')),
                ('descrizione_breve', models.TextField(max_length=300, verbose_name='Descrizione Breve')),
                ('descrizione_completa', models.TextField(verbose_name='Descrizione Completa')),
                ('prezzo_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo Minimo (€)')),
                ('prezzo_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo Massimo (€)')),
                ('durata_giorni_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durata Minima (giorni)')),
                ('durata_giorni_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durata Massima (giorni)')),
                ('difficolta', models.CharField(choices=[('facile', 'Facile'), ('media', 'Media'), ('difficile', 'Difficile')], default='media', max_length=10, verbose_name='Difficoltà')),
                ('include_progetto', models.BooleanField(default=True, verbose_name='Include Progetto')),
                ('include_pratiche', models.BooleanField(default=True, verbose_name='Include Gestione Pratiche')),
                ('include_bonus', models.BooleanField(default=False, verbose_name='Gestione Bonus Fiscali')),
                ('immagine_principale', models.ImageField(upload_to='pacchetti/', verbose_name='Immagine Principale')),
                ('immagine_prima', models.ImageField(blank=True, null=True, upload_to='pacchetti/prima/', verbose_name='Foto Prima')),
                ('immagine_dopo', models.ImageField(blank=True, null=True, upload_to='pacchetti/dopo/', verbose_name='Foto Dopo')),
                ('attivo', models.BooleanField(default=True, verbose_name='Pacchetto Attivo')),
                ('in_evidenza', models.BooleanField(default=False, verbose_name='In Evidenza')),
                ('ordinamento', models.IntegerField(default=0, verbose_name='Ordine')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacchetti', to='core.categoriaintervento')),
            ],
            options={
                'verbose_name': 'Pacchetto Ristrutturazione',
                'verbose_name_plural': 'Pacchetti Ristrutturazione',
                'ordering': ['ordinamento', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ElementoPacchetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Elemento')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('incluso', models.BooleanField(default=True, verbose_name='Incluso nel Prezzo')),
                ('opzionale', models.BooleanField(default=False, verbose_name='Elemento Opzionale')),
                ('costo_aggiuntivo', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo Aggiuntivo (€)')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine')),
                ('pacchetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi', to='core.pacchettoristrutturazione')),
            ],
            options={
                'verbose_name': 'Elemento Pacchetto',
                'verbose_name_plural': 'Elementi Pacchetto',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosiImmobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_immobile', models.ImageField(upload_to='diagnosi/foto/', verbose_name='Foto Immobile')),
                ('planimetria', models.ImageField(blank=True, null=True, upload_to='diagnosi/planimetrie/', verbose_name='Planimetria')),
                ('note_utente', models.TextField(blank=True, verbose_name='Note e Richieste Specifiche')),
                ('stato', models.CharField(choices=[('in_elaborazione', 'In Elaborazione'), ('completata', 'Completata'), ('errore', 'Errore')], default='in_elaborazione', max_length=20, verbose_name='Stato Elaborazione')),
                ('problemi_strutturali', models.TextField(blank=True, verbose_name='Problemi Strutturali')),
                ('problemi_elettrici', models.TextField(blank=True, verbose_name='Problemi Elettrici')),
                ('problemi_idraulici', models.TextField(blank=True, verbose_name='Problemi Idraulici')),
                ('problemi_termici', models.TextField(blank=True, verbose_name='Problemi di Isolamento')),
                ('stato_generale', models.CharField(blank=True, choices=[('ottimo', 'Ottimo'), ('buono', 'Buono'), ('discreto', 'Discreto'), ('da_ristrutturare', 'Da Ristrutturare'), ('pessimo', 'Pessimo')], max_length=20, verbose_name='Stato Generale')),
                ('priorita_intervento', models.CharField(blank=True, choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=10, verbose_name='Priorità Intervento')),
                ('stima_costi_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stima Costi Minimi (€)')),
                ('stima_costi_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stima Costi Massimi (€)')),
                ('stima_tempo_giorni', models.IntegerField(blank=True, null=True, verbose_name='Stima Tempo (giorni)')),
                ('bonus_applicabili', models.TextField(blank=True, verbose_name='Bonus Fiscali Applicabili')),
                ('report_completo', models.TextField(blank=True, verbose_name='Report Completo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_completamento', models.DateTimeField(blank=True, null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosi', to=settings.AUTH_USER_MODEL)),
                ('pacchetti_consigliati', models.ManyToManyField(blank=True, to='core.pacchettoristrutturazione', verbose_name='Pacchetti Consigliati')),
            ],
            options={
                'verbose_name': 'Diagnosi Immobile',
                'verbose_name_plural': 'Diagnosi Immobili',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
