# Generated by Django 5.2.3 on 2025-06-30 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('card', 'Carta di Credito/Debito'), ('bank_transfer', 'Bonifico Bancario'), ('paypal', 'PayPal')], max_length=20)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('exp_month', models.PositiveIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveIntegerField(blank=True, null=True)),
                ('dettagli_aggiuntivi', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodi_pagamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metodo di Pagamento',
                'verbose_name_plural': 'Metodi di Pagamento',
                'ordering': ['-is_default', '-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ordine', models.CharField(editable=False, max_length=20, unique=True)),
                ('indirizzo_immobile', models.CharField(max_length=255)),
                ('citta', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=5)),
                ('superficie_mq', models.PositiveIntegerField()),
                ('note_aggiuntive', models.TextField(blank=True)),
                ('prezzo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costi_aggiuntivi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sconto_applicato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('in_attesa', 'In Attesa di Pagamento'), ('pagato', 'Pagato'), ('confermato', 'Confermata'), ('in_lavorazione', 'In Lavorazione'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='in_attesa', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'In Attesa'), ('processing', 'In Elaborazione'), ('succeeded', 'Completato'), ('failed', 'Fallito'), ('canceled', 'Annullato'), ('refunded', 'Rimborsato')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_inizio_prevista', models.DateField(blank=True, null=True)),
                ('data_fine_prevista', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to=settings.AUTH_USER_MODEL)),
                ('pacchetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='core.pacchettoristrutturazione')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoRata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rata', models.PositiveIntegerField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_scadenza', models.DateField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('processing', 'In Elaborazione'), ('succeeded', 'Completato'), ('failed', 'Fallito'), ('canceled', 'Annullato')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('descrizione', models.CharField(max_length=200)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='core.ordine')),
            ],
            options={
                'verbose_name': 'Pagamento Rata',
                'verbose_name_plural': 'Pagamenti Rate',
                'ordering': ['numero_rata'],
                'unique_together': {('ordine', 'numero_rata')},
            },
        ),
    ]
