# Generated by Django 5.2.3 on 2025-06-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metodopagamento_ordine_pagamentorata'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosiimmobile',
            name='foto_modernizzate_ai',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Modernizzate AI (JSON)'),
        ),
        migrations.AddField(
            model_name='diagnosiimmobile',
            name='punteggio_generale',
            field=models.FloatField(blank=True, null=True, verbose_name='Punteggio Generale (1-5)'),
        ),
        migrations.AddField(
            model_name='diagnosiimmobile',
            name='risultati_ai',
            field=models.TextField(blank=True, null=True, verbose_name='Risultati Analisi AI (JSON)'),
        ),
        migrations.AddField(
            model_name='diagnosiimmobile',
            name='stato_elaborazione',
            field=models.CharField(choices=[('in_elaborazione', 'In Elaborazione'), ('completata', 'Completata'), ('errore', 'Errore')], default='in_elaborazione', max_length=20, verbose_name='Stato Elaborazione AI'),
        ),
    ]
