# Generated by Django 5.2.3 on 2025-06-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diagnosiimmobile_foto_modernizzate_ai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosiimmobile',
            name='foto_modernizzate_ai',
        ),
        migrations.RemoveField(
            model_name='diagnosiimmobile',
            name='punteggio_generale',
        ),
        migrations.RemoveField(
            model_name='diagnosiimmobile',
            name='risultati_ai',
        ),
        migrations.RemoveField(
            model_name='diagnosiimmobile',
            name='stato_elaborazione',
        ),
    ]
