# Generated by Django 5.2.3 on 2025-06-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('impresa', 'Impresa'), ('artigiano', 'Artigiano'), ('admin', 'Amministratore')], default='cliente', max_length=15, verbose_name='Tipo Utente'),
        ),
    ]
