# Generated by Django 5.2.3 on 2025-06-30 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigiani', '0002_appuntamento_eccezioneorario_orariodisponibilita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoArtigiano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('documento_identita', 'Documento di Identità'), ('patente', 'Patente di Guida'), ('codice_fiscale', 'Codice Fiscale'), ('partita_iva', 'Partita IVA'), ('visura_camerale', 'Visura Camerale'), ('certificato_competenza', 'Certificato di Competenza'), ('attestato_corso', 'Attestato Corso Professionale'), ('licenza_lavoro', 'Licenza/Abilitazione'), ('assicurazione', 'Assicurazione Professionale'), ('altro', 'Altro Documento')], max_length=30, verbose_name='Tipo Documento')),
                ('file_documento', models.FileField(upload_to='artigiani/documenti/', verbose_name='File Documento')),
                ('nome_file', models.CharField(max_length=255, verbose_name='Nome File')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True, verbose_name='Data Caricamento')),
                ('data_scadenza', models.DateField(blank=True, null=True, verbose_name='Data Scadenza')),
                ('stato_verifica', models.CharField(choices=[('in_attesa', 'In Attesa di Verifica'), ('verificato', 'Verificato'), ('rifiutato', 'Rifiutato'), ('scaduto', 'Scaduto')], default='in_attesa', max_length=15, verbose_name='Stato Verifica')),
                ('note_verifica', models.TextField(blank=True, verbose_name='Note Verifica')),
                ('data_verifica', models.DateTimeField(blank=True, null=True, verbose_name='Data Verifica')),
                ('artigiano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='artigiani.profiloartigiano', verbose_name='Artigiano')),
                ('verificato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_verificati', to=settings.AUTH_USER_MODEL, verbose_name='Verificato Da')),
            ],
            options={
                'verbose_name': 'Documento Artigiano',
                'verbose_name_plural': 'Documenti Artigiani',
                'ordering': ['-data_caricamento'],
            },
        ),
        migrations.CreateModel(
            name='MessaggioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome Cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email Cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, verbose_name='Telefono Cliente')),
                ('oggetto', models.CharField(max_length=200, verbose_name='Oggetto')),
                ('messaggio', models.TextField(verbose_name='Messaggio')),
                ('data_invio', models.DateTimeField(auto_now_add=True, verbose_name='Data Invio')),
                ('stato', models.CharField(choices=[('nuovo', 'Nuovo'), ('letto', 'Letto'), ('risposto', 'Risposto'), ('archiviato', 'Archiviato')], default='nuovo', max_length=15, verbose_name='Stato Messaggio')),
                ('risposta', models.TextField(blank=True, verbose_name='Risposta')),
                ('data_risposta', models.DateTimeField(blank=True, null=True, verbose_name='Data Risposta')),
                ('artigiano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_ricevuti', to='artigiani.profiloartigiano', verbose_name='Artigiano')),
            ],
            options={
                'verbose_name': 'Messaggio Cliente',
                'verbose_name_plural': 'Messaggi Clienti',
                'ordering': ['-data_invio'],
            },
        ),
        migrations.CreateModel(
            name='SuggerimentoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_suggerimento', models.CharField(choices=[('profilo_incompleto', 'Profilo Incompleto'), ('foto_mancanti', 'Foto Mancanti'), ('descrizione_migliorabile', 'Descrizione Migliorabile'), ('prezzi_non_competitivi', 'Prezzi Non Competitivi'), ('risposta_lenta', 'Risposta Lenta ai Clienti'), ('recensioni_negative', 'Recensioni Negative'), ('documenti_scaduti', 'Documenti Scaduti'), ('video_consigliato', 'Video Consigliato'), ('certificazione_mancante', 'Certificazione Mancante'), ('zona_espansione', 'Zona di Espansione')], max_length=30, verbose_name='Tipo Suggerimento')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo Suggerimento')),
                ('descrizione', models.TextField(verbose_name='Descrizione Suggerimento')),
                ('azione_consigliata', models.TextField(verbose_name='Azione Consigliata')),
                ('priorita', models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=10, verbose_name='Priorità')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('letto', models.BooleanField(default=False, verbose_name='Letto')),
                ('applicato', models.BooleanField(default=False, verbose_name='Applicato')),
                ('data_applicazione', models.DateTimeField(blank=True, null=True, verbose_name='Data Applicazione')),
                ('artigiano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggerimenti_ia', to='artigiani.profiloartigiano', verbose_name='Artigiano')),
            ],
            options={
                'verbose_name': 'Suggerimento IA',
                'verbose_name_plural': 'Suggerimenti IA',
                'ordering': ['-priorita', '-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='VideoArtigiano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo Video')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('tipo_video', models.CharField(choices=[('presentazione', 'Video di Presentazione'), ('lavoro_in_corso', 'Lavoro in Corso'), ('lavoro_completato', 'Lavoro Completato'), ('testimonial', 'Testimonial Cliente'), ('tutorial', 'Tutorial/Dimostrazione')], default='presentazione', max_length=20, verbose_name='Tipo Video')),
                ('file_video', models.FileField(help_text='Formati supportati: MP4, AVI, MOV (max 100MB)', upload_to='artigiani/video/', verbose_name='File Video')),
                ('miniatura', models.ImageField(blank=True, upload_to='artigiani/miniature/', verbose_name='Miniatura Video')),
                ('durata', models.IntegerField(blank=True, null=True, verbose_name='Durata (secondi)')),
                ('in_evidenza', models.BooleanField(default=False, verbose_name='In Evidenza')),
                ('pubblico', models.BooleanField(default=True, verbose_name='Pubblico nel Profilo')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True, verbose_name='Data Caricamento')),
                ('visualizzazioni', models.IntegerField(default=0, verbose_name='Visualizzazioni')),
                ('artigiano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='artigiani.profiloartigiano', verbose_name='Artigiano')),
            ],
            options={
                'verbose_name': 'Video Artigiano',
                'verbose_name_plural': 'Video Artigiani',
                'ordering': ['-in_evidenza', '-data_caricamento'],
            },
        ),
        migrations.CreateModel(
            name='CertificazioneArtigiano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_certificazione', models.CharField(choices=[('identita_verificata', 'Identità Verificata'), ('documenti_verificati', 'Documenti Verificati'), ('competenze_verificate', 'Competenze Verificate'), ('assicurazione_attiva', 'Assicurazione Attiva'), ('recensioni_positive', 'Recensioni Positive'), ('lavori_completati', 'Lavori Completati'), ('risposta_rapida', 'Risposta Rapida'), ('prezzo_trasparente', 'Prezzo Trasparente'), ('professionista_premium', 'Professionista Premium')], max_length=30, verbose_name='Tipo Certificazione')),
                ('attiva', models.BooleanField(default=True, verbose_name='Certificazione Attiva')),
                ('data_ottenimento', models.DateTimeField(auto_now_add=True, verbose_name='Data Ottenimento')),
                ('data_scadenza', models.DateField(blank=True, null=True, verbose_name='Data Scadenza')),
                ('punteggio', models.IntegerField(default=10, verbose_name='Punteggio Badge')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione Certificazione')),
                ('artigiano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificazioni', to='artigiani.profiloartigiano', verbose_name='Artigiano')),
            ],
            options={
                'verbose_name': 'Certificazione Artigiano',
                'verbose_name_plural': 'Certificazioni Artigiani',
                'ordering': ['-data_ottenimento'],
                'unique_together': {('artigiano', 'tipo_certificazione')},
            },
        ),
    ]
